### ISSUE TITLE
Failed build on FreeBSD 13.2

### ISSUE THREAD

**Issue by alexax66** [shmuz/far2m#44]
Сборка far2m  под FreeBSD 13.2  с ключами cmake по умолчанию завершается с ошибкой:

```
[265/774] Building C object luafar/CMakeFiles/luafar.dir/src/mytimer.c.o
FAILED: luafar/CMakeFiles/luafar.dir/src/mytimer.c.o 
/usr/bin/cc -DFAR_DONT_USE_INTERNALS -DWINPORT_DIRECT -Dluafar_EXPORTS -I/home/alexax/src/far2l-shmuz-2/utils/include -I/usr/local/include/luajit-2.1 -I/home/alexax/src/far2l-shmuz-2/far/far2sdk -I/home/alexax/src/far2l-shmuz-2/WinPort -Wall -std=c99 -fPIC -Wno-unused-function -D_FILE_OFFSET_BITS=64 -ffunction-sections -fdata-sections -DWINPORT_REGISTRY  -Wall -std=c99 -fPIC -Wno-unused-function -D_FILE_OFFSET_BITS=64 -O2 -std=gnu11 -fPIC -fvisibility=hidden -MD -MT luafar/CMakeFiles/luafar.dir/src/mytimer.c.o -MF luafar/CMakeFiles/luafar.dir/src/mytimer.c.o.d -o luafar/CMakeFiles/luafar.dir/src/mytimer.c.o -c /home/alexax/src/far2l-shmuz-2/luafar/src/mytimer.c
/home/alexax/src/far2l-shmuz-2/luafar/src/mytimer.c:5:10: fatal error: 'sys/timerfd.h' file not found
#include <sys/timerfd.h>
         ^~~~~~~~~~~~~~~
1 error generated.
[267/774] Building C object luafar/CMakeFiles/luafar.dir/src/ustring.c.o
FAILED: luafar/CMakeFiles/luafar.dir/src/ustring.c.o 
/usr/bin/cc -DFAR_DONT_USE_INTERNALS -DWINPORT_DIRECT -Dluafar_EXPORTS -I/home/alexax/src/far2l-shmuz-2/utils/include -I/usr/local/include/luajit-2.1 -I/home/alexax/src/far2l-shmuz-2/far/far2sdk -I/home/alexax/src/far2l-shmuz-2/WinPort -Wall -std=c99 -fPIC -Wno-unused-function -D_FILE_OFFSET_BITS=64 -ffunction-sections -fdata-sections -DWINPORT_REGISTRY  -Wall -std=c99 -fPIC -Wno-unused-function -D_FILE_OFFSET_BITS=64 -O2 -std=gnu11 -fPIC -fvisibility=hidden -MD -MT luafar/CMakeFiles/luafar.dir/src/ustring.c.o -MF luafar/CMakeFiles/luafar.dir/src/ustring.c.o.d -o luafar/CMakeFiles/luafar.dir/src/ustring.c.o -c /home/alexax/src/far2l-shmuz-2/luafar/src/ustring.c
/home/alexax/src/far2l-shmuz-2/luafar/src/ustring.c:1:10: fatal error: 'uuid/uuid.h' file not found
#include <uuid/uuid.h>
         ^~~~~~~~~~~~~
1 error generated.

```

Если отключть сборку плагина lua  (-DUSELUA=NO), то  процесс завершается с ошибкой:
```
[388/502] Building CXX object netcfg/CMakeFiles/netcfg.dir/src/netif/netif.cpp.o
FAILED: netcfg/CMakeFiles/netcfg.dir/src/netif/netif.cpp.o 
/usr/bin/c++ -DFAR_DONT_USE_INTERNALS -DUNICODE -DUSEUCD=OFF -DWINPORT_DIRECT -Dnetcfg_EXPORTS -I/home/alexax/src/far2l-shmuz-2/utils/include -I/home/alexax/src/far2l-shmuz-2/netcfg/src -I/home/alexax/src/far2l-shmuz-2/far/far2sdk -I/home/alexax/src/far2l-shmuz-2/WinPort -Wall -fPIC -Wno-unused-function -D_FILE_OFFSET_BITS=64 -ffunction-sections -fdata-sections -DWINPORT_REGISTRY -Wall  -Wall -fPIC -Wno-unused-function -D_FILE_OFFSET_BITS=64 -O2 -std=c++17 -fPIC -fvisibility=hidden -MD -MT netcfg/CMakeFiles/netcfg.dir/src/netif/netif.cpp.o -MF netcfg/CMakeFiles/netcfg.dir/src/netif/netif.cpp.o.d -o netcfg/CMakeFiles/netcfg.dir/src/netif/netif.cpp.o -c /home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp
In file included from /home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:6:
In file included from /home/alexax/src/far2l-shmuz-2/netcfg/src/common/netutils.h:15:
/usr/include/net/route.h:64:18: error: field has incomplete type 'struct sockaddr'
        struct  sockaddr ro_dst;
                         ^
/usr/include/net/route.h:64:9: note: forward declaration of 'sockaddr'
        struct  sockaddr ro_dst;
                ^
In file included from /home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:6:
In file included from /home/alexax/src/far2l-shmuz-2/netcfg/src/common/netutils.h:16:
/usr/include/net/if_arp.h:90:18: error: field has incomplete type 'struct sockaddr'
        struct  sockaddr arp_pa;                /* protocol address */
                         ^
/usr/include/net/route.h:64:9: note: forward declaration of 'sockaddr'
        struct  sockaddr ro_dst;
                ^
In file included from /home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:6:
In file included from /home/alexax/src/far2l-shmuz-2/netcfg/src/common/netutils.h:16:
/usr/include/net/if_arp.h:91:18: error: field has incomplete type 'struct sockaddr'
        struct  sockaddr arp_ha;                /* hardware address */
                         ^
/usr/include/net/route.h:64:9: note: forward declaration of 'sockaddr'
        struct  sockaddr ro_dst;
                ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:605:41: error: use of undeclared identifier 'NET_RT_IFLIST2'
        int mib[6] = {CTL_NET, PF_ROUTE, 0, 0, NET_RT_IFLIST2, 0};
                                               ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:629:25: error: use of undeclared identifier 'RTM_IFINFO2'
                        if( ifm->ifm_type == RTM_IFINFO2 ) {
                                             ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:631:59: error: arithmetic on a pointer to an incomplete type 'struct if_msghdr2'
                                struct sockaddr_dl *sdl = (struct sockaddr_dl *)(if2m + 1);
                                                                                 ~~~~ ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:630:12: note: forward declaration of 'if_msghdr2'
                                struct if_msghdr2 *if2m = (struct if_msghdr2 *)ifm;
                                       ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:634:22: error: member access into incomplete type 'struct if_msghdr2'
                                        ifa_flags = if2m->ifm_flags;
                                                        ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:630:12: note: forward declaration of 'if_msghdr2'
                                struct if_msghdr2 *if2m = (struct if_msghdr2 *)ifm;
                                       ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:635:25: error: member access into incomplete type 'struct if_msghdr2'
                                        send_packets = if2m->ifm_data.ifi_opackets;
                                                           ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:630:12: note: forward declaration of 'if_msghdr2'
                                struct if_msghdr2 *if2m = (struct if_msghdr2 *)ifm;
                                       ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:636:25: error: member access into incomplete type 'struct if_msghdr2'
                                        recv_packets = if2m->ifm_data.ifi_ipackets;
                                                           ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:630:12: note: forward declaration of 'if_msghdr2'
                                struct if_msghdr2 *if2m = (struct if_msghdr2 *)ifm;
                                       ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:637:23: error: member access into incomplete type 'struct if_msghdr2'
                                        send_bytes = if2m->ifm_data.ifi_obytes;
                                                         ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:630:12: note: forward declaration of 'if_msghdr2'
                                struct if_msghdr2 *if2m = (struct if_msghdr2 *)ifm;
                                       ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:638:23: error: member access into incomplete type 'struct if_msghdr2'
                                        recv_bytes = if2m->ifm_data.ifi_ibytes;
                                                         ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:630:12: note: forward declaration of 'if_msghdr2'
                                struct if_msghdr2 *if2m = (struct if_msghdr2 *)ifm;
                                       ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:639:23: error: member access into incomplete type 'struct if_msghdr2'
                                        send_errors =if2m->ifm_data.ifi_oerrors;
                                                         ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:630:12: note: forward declaration of 'if_msghdr2'
                                struct if_msghdr2 *if2m = (struct if_msghdr2 *)ifm;
                                       ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:640:24: error: member access into incomplete type 'struct if_msghdr2'
                                        recv_errors = if2m->ifm_data.ifi_ierrors;
                                                          ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:630:12: note: forward declaration of 'if_msghdr2'
                                struct if_msghdr2 *if2m = (struct if_msghdr2 *)ifm;
                                       ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:641:23: error: member access into incomplete type 'struct if_msghdr2'
                                        collisions = if2m->ifm_data.ifi_collisions;
                                                         ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:630:12: note: forward declaration of 'if_msghdr2'
                                struct if_msghdr2 *if2m = (struct if_msghdr2 *)ifm;
                                       ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:642:22: error: member access into incomplete type 'struct if_msghdr2'
                                        multicast = if2m->ifm_data.ifi_imcasts + if2m->ifm_data.ifi_omcasts;
                                                        ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:630:12: note: forward declaration of 'if_msghdr2'
                                struct if_msghdr2 *if2m = (struct if_msghdr2 *)ifm;
                                       ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:642:51: error: member access into incomplete type 'struct if_msghdr2'
                                        multicast = if2m->ifm_data.ifi_imcasts + if2m->ifm_data.ifi_omcasts;
                                                                                     ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:630:12: note: forward declaration of 'if_msghdr2'
                                struct if_msghdr2 *if2m = (struct if_msghdr2 *)ifm;
                                       ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:643:16: error: member access into incomplete type 'struct if_msghdr2'
                                        mtu = if2m->ifm_data.ifi_mtu;
                                                  ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:630:12: note: forward declaration of 'if_msghdr2'
                                struct if_msghdr2 *if2m = (struct if_msghdr2 *)ifm;
                                       ^
/home/alexax/src/far2l-shmuz-2/netcfg/src/netif/netif.cpp:664:56: error: use of undeclared identifier 'IFF_NOTRAILERS'
bool NetInterface::IsNotrailers() { return ifa_flags & IFF_NOTRAILERS; };
                                                       ^
18 errors generated.
ninja: build stopped: subcommand failed.
```

**Comment by shmuz** [comment]
По поводу ошибок с плагином netcfg может быть имеет смысл открыть тикет у автора: https://github.com/VPROFi/netcfgplugin

**Comment by alexax66** [comment]
Да, я так тоже думаю,  с ним были теже проблемы (и не только) и про попытке сборки в far2l под Freebsd.
Я вот только не нашел как отключить этот плагин при вызове cmake

**Comment by shmuz** [comment]
Отключить (в far2m) должно быть так:
`cmake NETCFG=no ..`
Но другие проблемы надо будет решать.

**Comment by shmuz** [comment]
Отредактировано пред. сообшение.

**Comment by shmuz** [comment]
Вот насчёт этого непонятно:
`/home/alexax/src/far2l-shmuz-2/luafar/src/ustring.c:1:10: fatal error: 'uuid/uuid.h' file not found`

вот здесь на ссылке по FreeBSD указано `#include <uuid/uuid.h>`
https://man.freebsd.org/cgi/man.cgi?query=uuid_generate&apropos=0&sektion=3&manpath=FreeBSD+13.1-RELEASE+and+Ports&arch=default&format=html

**Comment by shmuz** [comment]
Вот ответ от Chat GPT:

If you encounter the "fatal error: 'uuid/uuid.h' file not found" on FreeBSD, it
means that the system is missing the necessary header files for the UUID
library. To fix this issue, you can follow these steps:

1. Install the required package: Open a terminal and run the following command
to install the necessary package that contains the UUID header files:
 ```
sudo pkg install ossp-uuid
```
2. Verify the installation: After the package installation completes,
verify if the UUID header files are now available. Check if the file
`uuid/uuid.h` exists in the system by running the following command:
```
ls /usr/local/include/uuid/uuid.h
```
If the file is listed, it means the installation was successful.

**Comment by shmuz** [comment]
Задал тот же вопрос на другой системе, получил другой ответ, так что пробуйте оба варианта:

If you encounter the error `'uuid/uuid.h' file not found` on FreeBSD, it means
that the header file for the UUID library is missing or not properly installed.
To fix this error, you can follow these steps:

1. Install the necessary package: On FreeBSD, the UUID library is provided by
the `e2fsprogs-libuuid` package. To install it, open a terminal and run the
following command as the root user or with sudo privileges:
```
pkg install e2fsprogs-libuuid
```

2. Verify the installation: After the package installation is complete, verify
that the `uuid/uuid.h` header file is now available on your system. You can
check its presence by navigating to the `/usr/local/include` directory and
looking for the `uuid` directory. Inside the `uuid` directory, the `uuid.h`
file should be present.

3. Update the include path: If the `uuid/uuid.h` file is still not found even
after installing the package, you may need to update the include path in your
code or build configuration. Modify the include statement in your code to use
the correct path. For example, change:
```c
#include <uuid/uuid.h>
```
to:
```c
#include <uuid.h>
```
or specify the full path to the header file.

4. Recompile your code: After making the necessary changes, recompile your code
and ensure that the build process can find the `uuid/uuid.h` header file.

By following these steps, you should be able to resolve the `'uuid/uuid.h' file
not found` error on FreeBSD.

**Comment by alexax66** [comment]
1. С этим ключём cmake -DNETCFG=no .. собралось и работает, пока lua плагин  отключен.
2. Пакет e2fsprogs-libuuid у меня был установлен
3. Как будет время попробую вариант с sudo pkg install ossp-uuid, если не поможет то скорее всего придется вносить правки: вместо   #include <uuid/uuid.h> поменять  на #include <uuid.h>

**Comment by shmuz** [comment]
Пункт 4 если не удастся пофиксить - исключим из компиляции, пожертвовав функцией far.Timer.
А вот что говорит ChatGPT:

To fix the "fatal error: 'sys/timerfd.h' file not found" issue on FreeBSD, you
can follow these steps:

1. Check the availability of the header file: First, verify if the `timerfd.h`
header file is present on your system. Run the following command to check if
the file exists:
   ```
   ls /usr/include/sys/timerfd.h
   ```

   If the file is not found, it means that the header file is not available on
your system. In that case, you may need to consider an alternative solution or
update your system.

2. Update your system: Ensure that your FreeBSD system is up to date by running
the following commands:
   ```
   sudo freebsd-update fetch
   sudo freebsd-update install
   ```

   This will update your system with the latest patches and updates.

3. Install necessary packages: If the `timerfd.h` header file is missing, you
may need to install additional packages that provide it. Run the following
command to install the necessary package:
   ```
   sudo pkg install libevent2
   ```

4. Update include paths: If the header file is still not found, you may need to
update the include paths in your build system or makefile. Add the following
include path to your build configuration:
   ```
   -I/usr/local/include
   ```

   This will ensure that the compiler can find the necessary header files.

5. Retry the build: After completing the above steps, try rebuilding your
program or project. The "fatal error: 'sys/timerfd.h' file not found" issue
should be resolved.

By following these steps, you should be able to fix the "fatal error:
'sys/timerfd.h' file not found" issue on FreeBSD.

**Comment by shmuz** [comment]
Поставил себе на виртуалку GhostBSD.

Сейчас (после сегодняшних коммитов) должно всё собираться (кроме плагина NetCfg, но его можно запретить).
1. Устанавливать дополнительно ничего не надо.
2. Функция far.Timer пока недоступна, но это редкоиспользуемая функция.
3. Функцию, связанную с ошибкой <uuid/uuid.h> я переписал, она собирается, но ещё не отлаживалась.

Обнаружил очень серьёзную неисправность: на GhostBSD ни в far2m, ни в far2l не работают команды, запускаемые из комстроки, например `ls` или `pwd`. Пожалуйста проверьте, работает ли это на FreeBSD.

**Comment by alexax66** [comment]
Да, это извсетнаяпроблем если собирать из исходников 
Решается она просто, установкой пакета bash и желательно сделать симлинк  /usr/bin/bash на /bin/bash

**Comment by alexax66** [comment]
у меня пока нет времени заняться проверкой как будет собираться far2m после внесенных изменений

**Comment by alexax66** [comment]
Все же получилсь собрать сегодня far2m c последними правками и включенным плагином luafar.
Теперь собралось без ошибок:
```
[753/753] /home/alexax/src/far2m/_build/copyright
Copyrighting: *
Copyrighting: colorer/*
Copyrighting: colorer/src/Colorer-library/src/colorer/unicode/x_tables_generator.pl colorer/src/Colorer-library/src/colorer/unicode/x_encodings.pl colorer/src/pcolorer2/*
Copyrighting: farlng/*
Copyrighting: compare/* drawline/* editcase/* align/* autowrap/* farftp/* FARStdlib/* filecase/* multiarc/* SimpleIndent/* tmppanel/*
Copyrighting: calc/*
Copyrighting: calc/src/shared/mathexpression/*
Copyrighting: calc/src/shared/ttmath/*
Copyrighting: calc/src/shared/trex/*
Copyrighting: editorcomp/*
Copyrighting: far2l/bootstrap/* far2l/fpsdk/* far2l/src/filelist.hpp far2l/src/cache.hpp far2l/src/exitcode.hpp far2l/src/dizlist.cpp far2l/src/plist.cpp far2l/src/panel.hpp far2l/src/LICENSE.Far2.txt far2l/src/flshow.cpp far2l/src/infolist.cpp far2l/src/fileview.cpp far2l/src/editor.hpp far2l/src/filetype.hpp far2l/src/hist/history.cpp far2l/src/DlgGuid.hpp far2l/src/message.hpp far2l/src/frame.cpp far2l/src/FilesSuggestor.cpp far2l/src/dizlist.hpp far2l/src/DialogBuilder.cpp far2l/src/DialogBuilder.hpp far2l/src/fileattr.hpp far2l/src/dialog.hpp far2l/src/plist.hpp far2l/src/filelist.cpp far2l/src/RefreshFrameManager.cpp far2l/src/copy.hpp far2l/src/fileowner.cpp far2l/src/flupdate.cpp far2l/src/setattr.cpp far2l/src/frame.hpp far2l/src/filetype.cpp far2l/src/RefreshFrameManager.hpp far2l/src/FarDlgBuilder.hpp far2l/src/qview.cpp far2l/src/plug/plugins.cpp far2l/src/plug/plugapi.cpp far2l/src/plug/PluginW.hpp far2l/src/plug/PluginA.cpp far2l/src/plug/plugins.hpp far2l/src/plug/wrap.cpp far2l/src/plug/PluginA.hpp far2l/src/plug/plclass.hpp far2l/src/plug/PluginW.cpp far2l/src/plug/plclass.cpp far2l/src/plug/plugapi.hpp far2l/src/foldtree.hpp far2l/src/headers.hpp far2l/src/TPreRedrawFunc.cpp far2l/src/lang.hpp far2l/src/locale/DetectCodepage.h far2l/src/locale/locale.cpp far2l/src/locale/locale.hpp far2l/src/locale/xlat.hpp far2l/src/locale/codepage.hpp far2l/src/locale/DetectCodepage.cpp far2l/src/locale/xlat.cpp far2l/src/locale/codepage.cpp far2l/src/vmenu.hpp far2l/src/viewer.cpp far2l/src/fnparce.cpp far2l/src/stddlg.cpp far2l/src/SafeMMap.cpp far2l/src/setcolor.cpp far2l/src/base/farqueue.hpp far2l/src/global.cpp far2l/src/hilight.cpp far2l/src/stddlg.hpp far2l/src/global.hpp far2l/src/execute.cpp far2l/src/datetime.cpp far2l/src/rdrwdsk.cpp far2l/src/edit.cpp far2l/src/TPreRedrawFunc.hpp far2l/src/keybar.hpp far2l/src/execute.hpp far2l/src/treelist.cpp far2l/src/findfile.cpp far2l/src/panel.cpp far2l/src/bookmarks/BookmarksMenu.cpp far2l/src/bookmarks/BookmarksLegacy.cpp far2l/src/SafeMMap.hpp far2l/src/FilesSuggestor.hpp far2l/src/hist/poscache.hpp far2l/src/filefilterparams.cpp far2l/src/farwinapi.hpp far2l/src/base/farqueue.cpp far2l/src/synchro.cpp far2l/src/filepanels.cpp far2l/src/viewer.hpp far2l/src/rdrwdsk.hpp far2l/src/fileedit.hpp far2l/src/menubar.cpp far2l/src/dirinfo.cpp far2l/src/filestr.cpp far2l/src/filepanels.hpp far2l/src/options.hpp far2l/src/hist/history.hpp far2l/src/infolist.hpp far2l/src/filefilter.cpp far2l/src/cmdline.cpp far2l/src/cfg/language.cpp far2l/src/flmodes.cpp far2l/src/filefilter.hpp far2l/src/findfile.hpp far2l/src/hmenu.cpp far2l/src/vmenu.cpp far2l/src/scantree.cpp far2l/src/syslog.hpp far2l/src/cmdline.hpp far2l/src/cfg/language.hpp far2l/src/dirinfo.hpp far2l/src/modal.cpp far2l/src/foldtree.cpp far2l/src/datetime.hpp far2l/src/ctrlobj.hpp far2l/src/clipboard.cpp far2l/src/delete.hpp far2l/src/dlgedit.cpp far2l/src/ctrlobj.cpp far2l/src/modal.hpp far2l/src/execute_oscmd.cpp far2l/src/mkdir.cpp far2l/src/namelist.cpp far2l/src/mkdir.hpp far2l/src/help.cpp far2l/src/fileowner.hpp far2l/src/Mounts.cpp far2l/src/copy.cpp far2l/src/synchro.hpp far2l/src/hist/poscache.cpp far2l/src/setattr.hpp far2l/src/flink.hpp far2l/src/filestr.hpp far2l/src/console/scrsaver.cpp far2l/src/console/scrobj.cpp far2l/src/console/grabber.hpp far2l/src/console/constitle.hpp far2l/src/console/palette.cpp far2l/src/console/palette.hpp far2l/src/console/scrsaver.hpp far2l/src/console/grabber.cpp far2l/src/console/savescr.cpp far2l/src/console/lockscrn.cpp far2l/src/console/scrbuf.hpp far2l/src/console/lockscrn.hpp far2l/src/console/savescr.hpp far2l/src/console/scrbuf.cpp far2l/src/console/interf.cpp far2l/src/console/interf.hpp far2l/src/console/constitle.cpp far2l/src/console/console.hpp far2l/src/console/scrobj.hpp far2l/src/console/keys.hpp far2l/src/console/keyboard.cpp far2l/src/console/keyboard.hpp far2l/src/console/console.cpp far2l/src/console/colors.hpp far2l/src/menubar.hpp far2l/src/mix/cddrv.hpp far2l/src/mix/RegExp.hpp far2l/src/mix/pathmix.cpp far2l/src/mix/chgprior.hpp far2l/src/base/farrtl.hpp far2l/src/mix/mix.hpp far2l/src/mix/format.hpp far2l/src/mix/wakeful.hpp far2l/src/mix/panelmix.hpp far2l/src/mix/drivemix.hpp far2l/src/mix/drivemix.cpp far2l/src/base/bitflags.hpp far2l/src/mix/RegExp.cpp far2l/src/mix/panelmix.cpp far2l/src/base/array.hpp far2l/src/mix/mix.cpp far2l/src/mix/strmix.cpp far2l/src/mix/cvtname.hpp far2l/src/base/farrtl.cpp far2l/src/mix/strmix.hpp far2l/src/base/DList.hpp far2l/src/mix/pathmix.hpp far2l/src/base/FARString.cpp far2l/src/mix/processname.cpp far2l/src/mix/processname.hpp far2l/src/base/DList.cpp far2l/src/mix/cddrv.cpp far2l/src/base/CriticalSections.hpp far2l/src/base/FARString.hpp far2l/src/mix/dirmix.hpp far2l/src/mix/udlist.cpp far2l/src/base/noncopyable.hpp far2l/src/mix/dirmix.cpp far2l/src/mix/udlist.hpp far2l/src/mix/cvtname.cpp far2l/src/mix/chgprior.cpp far2l/src/mix/format.cpp far2l/src/cfg/config.cpp far2l/src/cfg/config.hpp far2l/src/cfg/HotkeyLetterDialog.hpp far2l/src/cfg/HotkeyLetterDialog.cpp far2l/src/usermenu.hpp far2l/src/syslog.cpp far2l/src/Mounts.hpp far2l/src/setcolor.hpp far2l/src/namelist.hpp far2l/src/farwinapi.cpp far2l/src/options.cpp far2l/src/fileview.hpp far2l/src/delete.cpp far2l/src/clipboard.hpp far2l/src/farversion.h far2l/src/dlgedit.hpp far2l/src/panelctype.hpp far2l/src/manager.cpp far2l/src/filefilterparams.hpp far2l/src/message.cpp far2l/src/fileedit.cpp far2l/src/filemask/FileMasksWithExclude.cpp far2l/src/filemask/CFileMask.cpp far2l/src/filemask/CFileMask.hpp far2l/src/filemask/FileMasksProcessor.hpp far2l/src/filemask/FileMasksWithExclude.hpp far2l/src/filemask/FileMasksProcessor.cpp far2l/src/filemask/BaseFileMask.hpp far2l/src/editor.cpp far2l/src/hmenu.hpp far2l/src/manager.hpp far2l/src/fileattr.cpp far2l/src/hilight.hpp far2l/src/edit.hpp far2l/src/scantree.hpp far2l/src/treelist.hpp far2l/src/macro/TStack.hpp far2l/src/macro/tvar.hpp far2l/src/macro/chgmmode.cpp far2l/src/macro/macro.hpp far2l/src/macro/chgmmode.hpp far2l/src/macro/syntax.cpp far2l/src/macro/tvar.cpp far2l/src/macro/macro.cpp far2l/src/macro/macroopcode.hpp far2l/src/macro/syntax.hpp far2l/src/flink.cpp far2l/src/fnparce.hpp far2l/src/usermenu.cpp far2l/src/qview.hpp far2l/src/main.cpp far2l/src/DlgGuid.cpp far2l/src/flplugin.cpp far2l/src/keybar.cpp far2l/src/help.hpp far2l/src/dialog.cpp far2l/src/cache.cpp
Copyrighting: far2l/src/vt/vtansi.cpp
Copyrighting: multiarc/src/formats/rar/unrar/*
Copyrighting: multiarc/src/formats/ha/ha/*
Copyrighting: multiarc/src/formats/7z/C/* multiarc/src/formats/7z/7zMain.c
Copyrighting: NetRocks/*
Copyrighting: incsrch/*
Copyrighting: inside/*
Copyrighting: packaging/*
Copyrighting: python/*
Copyrighting: utils/* WinPort/*
Copyrighting: utils/include/ww898/*
alexax@ghostbsd-pc ~/s/f/_build (master)> 
```
![image](https://github.com/shmuz/far2m/assets/12674883/28207eee-fd5f-4248-ad0b-a6f86b208f2f)

**Comment by shmuz** [comment]
Я не знаю, пользовались ли вы в прошлом Lua в сочетании с Фаром.
Если нет, я могу вам помочь.
Потому что это, скажем так, основное отличие far2m от far2l.

**Comment by alexax66** [comment]
Да было бы интресно, я пока не нашел где и как включить палгины lua

**Comment by shmuz** [comment]
Лучше начать с макросов.
Следующая последовательность установит вам все мои макросы.
Это для демонстрации, потом вы уберёте те, что вам не нужны.
```
cd ~
git clone https://github.com/shmuz/luafar2m.git
rm -r ~/.config/far2m/Macros
ln -s ~/luafar2m/Macros ~/.config/far2m/Macros
```
Перезапустить Фар.
Нажать `CtrlShift5` - должен появиться календарь. Посмотреть, закрыть.
Нажать AltShiftF1 - должен появиться список всех макросов.
Если это всё получилось, можно идти дальше.

**Comment by akruphi** [comment]
> Обнаружил очень серьёзную неисправность: на GhostBSD ни в far2m, ни в far2l не работают команды, запускаемые из комстроки, например `ls` или `pwd`.

> Да, это известная проблема если собирать из исходников
> Решается она просто, установкой пакета bash (он есть в зависимостях при установки пакета far2l во FreeBSD)

Немного вклинюсь с offtop: в far2l предусмотрена замена shell через F9->Options->Command line settings->Use shell но это будет работать коряво - см.: https://github.com/elfmz/far2l/issues/1264#issuecomment-1045334082

**Comment by shmuz** [comment]
@akruphi, спасибо, это ценная для меня информация.

**Comment by alexax66** [comment]
Да я видел это https://github.com/elfmz/far2l/issues/1264#issuecomment-1045334082, но т.к. bash был установлен, проблем c командной строкой в FreeBSD и GhostBSD у меня не было и настройки я не менял.  А вот в DragonFly BSD эта проблема была пока не установил bash

**Comment by alexax66** [comment]
Проверил я работу far2m c lua скриптами.
Что то вызов CtrlShift5  и AltShiftF1 не работает. При запуске  far2m  что в графическом режиме, что в эмуляторе терминала,  что в локальной консоли (без X-ов), везде поведение одинаковое. 
Но  если войти через меню по F11 в список макросов, то  там скрипты  есть и даже некоторые запускаются.
Вчера это проделывал поздно вечером и уже  копаться в чем может быть проблема не стал

**Comment by shmuz** [comment]
Как вы наверняка знаете, в операционной системе ряд кнопкосочетаний назначен на разные действия (манипуляции с окнами и многие другие). Эмуляторы терминала имеют свои дополнительные назначения клавиш. Фару достаются только те сочетания, что остались. Это объясняет то, что в графическом режиме Фару доступно больше сочетаний клавиш, чем в режиме TTY.

Поскольку для меня работа с Фаром важнее, чем предлагаемые ОС действия, то я в соответствующем диалоге настроек ОС освобождаю большинство назначенных клавиш и сочетаний, после чего они начинают работать в Фаре.

Вторая возможность - открыть код макроса и переназначить его клавишу. Найти код макроса можно из списка макросов, нажав F4 на строчке того макроса, который вы хотите редактировать.
